version: '3.8'
services:
  app:
    build:
      context: .           # Build from the current folder
    ports:
      - "4200:4200"        # Map Angular's port
      - "3000:3000"        # Map Node.js backend port
    volumes:
      - .:/app             # Mount the current folder for live reload
    command: >
      sh -c "node server.js & ng serve --host 0.0.0.0 --port 4200"
