name: CI/CD Pipeline

on:
  push:
    branches:
      - ListHouses
  pull_request:
    branches:
      - ListHouses

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend/frontend  # Change directory to the frontend folder

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint

    - name: Run tests
      run: npm test -- --watch=false

    - name: Build project
      run: npm run build
