name: Docker Image CI

on:
  push:
    branches:
      - main
      - ListHouses
  pull_request:
    branches:
      - main
      - ListHouses

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code on this fresh ubuntu OS
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up a unique tag for our docker image
      id: tag
      run: echo "tag=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build ./frontend/frontend --file ./frontend/frontend/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/Unilease:${{ env.tag }}

    - name: Push the Docker image to our DockerHub repo
      run: docker push ${{ secrets.DOCKER_USERNAME }}/Unilease:${{ env.tag }}
